### ISSUE TITLE
onnx.optimizer removed from onnx==1.9.0, export function broken

### ISSUE THREAD

**Issue by mgumowsk** [ovextra/mmdetection#125]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
Traceback (most recent call last):
  File "/opt/mmdetection/tools/export.py", line 24, in <module>
    from onnx.optimizer import optimize
ModuleNotFoundError: No module named 'onnx.optimizer'

when using latest onnx==1.9.0

**Comment by Ilya-Krylov** [comment]
https://github.com/openvinotoolkit/mmdetection/pull/126
