### ISSUE TITLE
ONNX.md for document for exporting onnx models

### ISSUE THREAD

**Issue by lucasjinreal** [ovextra/mmdetection#34]
Can u guys write an ONNX.md file for how to exporting onnx models via OTEDetection?

It would be very much good if any instructions can be provided. So that community can using these onnx model for deployment on other platform.

**Comment by druzhkov-paul** [comment]
We can and [already have it](https://github.com/opencv/mmdetection/blob/ote/docs/GETTING_STARTED.md#export-pretrained-model).

**Comment by zr526799544** [comment]
I exporting the onnx models  via OTEDetection. you can use tools mmdetection-ote/export.py to export onnx model. and use mmdetection-ote/tools/test_exported.py to test your onnx model.

**Comment by zr526799544** [comment]
> Can u guys write an ONNX.md file for how to exporting onnx models via OTEDetection?
> 
> It would be very much good if any instructions can be provided. So that community can using these onnx model for deployment on other platform.

Do you exporting onnx models and test it's time? I use it and run onnx model through onnxruntime. It seems that the seed of onnx on onnxruntime in python has the same speed of mmdet in python.how to use onnx to accelerate inference??? would you like to give some advice???@druzhkov-paul

**Comment by zr526799544** [comment]
when I export onnx model and try to use it in opencv 4.2.0 but get error :/opencv/modules/dnn/src/onnx/onnx_importer.cpp:101: error: (-211:One of the arguments' values is out of range) Input is out of OpenCV 32S range in function 'convertInt64ToInt32'. would you mind give me some advice to solve it?

**Comment by druzhkov-paul** [comment]
@zr526799544 Could you please ask questions in relevant issues. And don't mind to open new ones, if there're no that're relevant yet. Thanks.

**Comment by druzhkov-paul** [comment]
> Do you exporting onnx models and test it's time? I use it and run onnx model through onnxruntime. It seems that the seed of onnx on onnxruntime in python has the same speed of mmdet in python.how to use onnx to accelerate inference??? would you like to give some advice???@druzhkov-paul

1. ONNXRuntime has multiple [execution providers](https://github.com/microsoft/onnxruntime#supported-accelerators), depending on which one you use and on the hardware configuration of you target machine you may experience deference inference speeds.
1. If your target is an Intel device (CPU, iGPU, VPU, etc.) I'd expect [OpenVINO toolkit](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit.html) to be the fastest option to use. Just try it.
1. Depending on your use case saying "higher speed" you may mean lower latency or higher throughput. Latency -- is how much time do you have to wait from the beginning of a single inference run till it's end. Throughput -- is how much images can you process in a certain amount of time. You can configure your inference engine to get either of these two. For more information please refer to [this guide](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Intro_to_Performance.html), for example.

**Comment by druzhkov-paul** [comment]
> when I export onnx model and try to use it in opencv 4.2.0 but get error :/opencv/modules/dnn/src/onnx/onnx_importer.cpp:101: error: (-211:One of the arguments' values is out of range) Input is out of OpenCV 32S range in function 'convertInt64ToInt32'. would you mind give me some advice to solve it?

Looks like an OpenCV issue. You may ask this question there, for quicker response. Thanks.
