### ISSUE TITLE
Remove the Initializer from the onnx model 

### ISSUE THREAD

**Issue by zr526799544** [ovextra/mmdetection#37]
**Motivation**
Remove the Initializer from the onnx model. It may speed up inference and avoid warning in onnxruntime in c++.

**Related resources**
def remove_initializer_from_input(modelpath):

    model = onnx.load(modelpath)
    if model.ir_version < 4:
        print(
            'Model with ir_version below 4 requires to include initilizer in graph input'
        )
        return
    print("remove_initializer_from_input")
    inputs = model.graph.input
    name_to_input = {}
    for input in inputs:
        name_to_input[input.name] = input

    for initializer in model.graph.initializer:
        if initializer.name in name_to_input:
            inputs.remove(name_to_input[initializer.name])

    onnx.save(model, modelpath)
copy from the https://github.com/microsoft/onnxruntime/blob/master/tools/python/remove_initializer_from_input.py

**Comment by druzhkov-paul** [comment]
Thanks. Some ONNX model polishing has been integrated into export script.
