### ISSUE TITLE
Code understanding help

### ISSUE THREAD

**Issue by zr526799544** [ovextra/mmdetection#42]
May you explain why has to rewrite topk, arrange clamp,and meshgrid func ? I check the pytorch doc and find it seem support in onnx officially.and tensor.view(1,-1) show up a lot. why reshape the tensor into shape(1,-1)?

**Comment by druzhkov-paul** [comment]
Some standard PyTorch primitives were wrapped to enable or extend their export capabilities. For example, `TopK` was wrapper with an extra piece of code that verifies that the number of element in provided `Tensor` complies with the given `K` value. This being said, please note, that this was originally tested with PyTorch/ONNX/ONNXRuntime/OpenVINO versions available at the moment, so revising the code with the latest dependencies' versions might be a good idea. We'll plan to do that after alignment with MMDetection 2.* is finished.

Regarding your point about reshape, it's hard to say, which one you are referring here.

**Comment by druzhkov-paul** [comment]
Export code has been revised to some extent for it to better use current PyTorch export capabilities when available. Though there always is a room for improvement. Contributions and/or motivated requests are always welcome.
