### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by HFVladimir** [ovextra/mmdetection#45]
HI! I've done installation steps as mentioned in readme.md and trying to run this script:
`python tools/export.py configs/htc/htc_r50_fpn_1x.py htc_r50_fpn_1x_20190408-878c1712.pth . onnx`.
Unfortunately, I've got the following error:
`RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at mmdet/ops/nms/src/nms_kernel.cu:111`

That I should do? My pytorch and cuda versions from conda:
```
torch==1.4.0
torchvision==0.5.0
cudatoolkit==10.2.89
```
My nvidia-smi info:
```
Driver Version: 418.87.01    
CUDA Version: 10.1
```
Thanks!

**Comment by druzhkov-paul** [comment]
@HFVladimir 

Obviously, your GPU driver is too old for CUDA 10.2. Please refer to [the table](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver) for driver compatibility details.

To fix the issue without upgrading the driver, you can try setting CUDA 10.1 as the one to be used:

```shell
export CUDA_HOME=/usr/local/cuda-10.1
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:$LD_LIBRARY_PATH
```

Meanwhile, I should warn you that HTC export is not supported yet.
