### ISSUE TITLE
Using dynamic input sizes in exported openvino models

### ISSUE THREAD

**Issue by LoaferCH** [ovextra/mmdetection#57]
Greetings. 
I have an issue that converting a model from openvino training extensions https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/object_detection/person-vehicle-bike-detection 
(using the pth checkpoint provided) results in me getting an error. I was following the exact guide on the page and converted a model to openvino. 
Trying to run openvino model with input_size other than 512x512 results in the following error 
```
Traceback (most recent call last):
  File "run_vino.py", line 88, in <module>
    model = Vino(config=config, num_proc=thred_num)
  File "run_vino.py", line 51, in __init__
    self.net.reshape({'image': (1, 3, config['shape'][1], config['shape'][0])})
  File "ie_api.pyx", line 1294, in openvino.inference_engine.ie_api.IENetwork.reshape
RuntimeError: IShapeInferExtension wasn't registered for node 636 with type ExperimentalDetectronPriorGridGenerator

```

 HOWEVER downloading a model from here https://download.01.org/opencv/ and reshaping it using inference engine totally works.

I was doing the following:

1. Run docker with openvino and mmdetection installed
2. Used mmdetection/tools/export.py to export the person-vehicle-bike-detection net.

python 3.7

**Comment by druzhkov-paul** [comment]
SSD models from Open Model Zoo are produced in `--alt_ssd_export` mode. Please try passing this flag to `export.py` script.

Another option would be to specify target resolution during export.

**Comment by LoaferCH** [comment]
> SSD models from Open Model Zoo are produced in `--alt_ssd_export` mode. Please try passing this flag to `export.py` script.
> 
> Another option would be to specify target resolution during export.

Thank you! Adding **--alt_ssd_export**  flag really helped.
