### ISSUE TITLE
Any plan for updating mmdet to the higher version?

### ISSUE THREAD

**Issue by shawn-xj** [ovextra/mmdetection#75]
**Describe the feature**
Hi, is there any plan for updating mmdet to higher version for example 2.2, 2.2.1 etc.
**Motivation**
Some bug from mmdet itself are fixed in higher version. And some new heads like pointrend head are supported by newer mmdet. 
Thanks!

**Comment by druzhkov-paul** [comment]
@shawn-xj We do have plans on merging the latest changes from the upstream repository, though we currently don't have a timeline for it.

@DmitriySidnev FYI

**Comment by shawn-xj** [comment]
> @shawn-xj We do have plans on merging the latest changes from the upstream repository, though we currently don't have a timeline for it.
> 
> @DmitriySidnev FYI

OK, many thanks.
