### ISSUE TITLE
keep_ratio=True support for OpenVINO models

### ISSUE THREAD

**Issue by kshpv** [ovextra/mmdetection#76]
Currently most of the two-stage detectors use keep_ratio=True config's option inside test and train pipelines. Unfortunately, using keep_ratio=True option leads to accuracy drop to 0% of the models in OpenVINO.

May you add keep_ratio=True support for exported OpenVINO models?

**Comment by druzhkov-paul** [comment]
@aleksei-kashapov Thanks, for reporting the issue. This is a known problem. The limitation came from the lack of reshape support for that kind of networks at the OpenVINO side. We'll fix the issue as soon as the CI is updated to the latest OpenVINO version.

**Comment by kshpv** [comment]
@DmitriySidnev if you have time, please fix the bug for Mask R-CNN models
Thanks!

**Comment by druzhkov-paul** [comment]
Implemented in #102.
