### ISSUE TITLE
Is it possible to upgrade torch==1.7.0 in requirements?

### ISSUE THREAD

**Issue by LeonidBeynenson** [ovextra/mmdetection#98]
Is it possible to upgrade pytorch version to `torch==1.7.0`  in this mmdetection?
(NB: at the moment `torch==1.5.1` is required here.)

The reason: at the moment nncf uses `torch==1.7.0`, so most probably in the nearest future some features of nncf will require this version of pytorch.
At the moment everything is ok, since
* nncf at the moment still works with `torch==1.5.1`
* nncf does not make check that `torch==1.7.0` (or `torch>=1.7.0`)

But the latter may be a bug that may be fixed in nncf .
And if they fix it, we will have to install `torch==1.7.0`, then install `nncf`, then reinstall `torch==1.5.1` -- ugly decision...

**Comment by LeonidBeynenson** [comment]
2 @aleksei-kashapov : FYI

**Comment by druzhkov-paul** [comment]
PyTorch versions 1.7.1 - 1.8.1 are supported now.
